### PR TITLE
Add color output

### PR DESCRIPTION
**Pull request by obazoud**

### CODE REVIEW

**Review by hoegertn — COMMENTED** [review]
This idea sounds great. Thanks. What do you think about a cli option to disable coloring? It might be useful for certain environments.

**Comment by atkinsonm** [comment]
Great idea @obazoud! @hoegertn agreed that an option to disable would be good. Perhaps enabled by default and disabled by a `--no-color` argument?

**Comment by atkinsonm** [comment]
@obazoud would it make sense to use  grey for the neutral statuses to match the AWS console? (that's hex 777 pulled from Chrome's inspector)

**Comment by obazoud** [comment]
Thanks!
- Argument added
- Improve color to match AWS Console

**Review by hoegertn — APPROVED** [review]

**Comment by hoegertn** [comment]
Released as 1.5.0

**Comment by hoegertn** [comment]
Released as 1.5.0

**Comment by hoegertn** [comment]
Released as 1.5.0

**Comment by hoegertn** [comment]
Released as 1.5.0

**Pull request merged**
